{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.metrics.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml .Values.metrics.serviceMonitor.annotations | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 15s
      scrapeTimeout: 14s
      {{- if .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.metrics.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.metrics.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
    - port: prometheus
      path: /metrics/detailed
      interval: 15s
      scrapeTimeout: 14s
      params:
        family:
          - queue_coarse_metrics
          - queue_metrics
          - node_coarse_metrics
          - node_metrics
          - connection_metrics
      {{- if .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.metrics.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.metrics.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
  selector:
    matchLabels:
      {{- include "rabbitmq.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- if .Values.metrics.serviceMonitor.honorLabels }}
  honorLabels: true
  {{- end }}
{{- end }}