apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-headless
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
    service.kubernetes.io/name: rabbitmq
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None # Headless service
  publishNotReadyAddresses: true
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: management
      port: 15672
      targetPort: management
      protocol: TCP
    - name: metrics
      port: 15692
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
    service.kubernetes.io/name: rabbitmq
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "15692"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: management
      port: 15672
      targetPort: management
      protocol: TCP
    - name: metrics
      port: 15692
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq